show correct error on incorrect encoding
tecnickcom/TCPDF pull request #594
Opened 2023-03-07 11:25 UTC by rubo77

E.G if you try this:

    $pdf->multiCell(0, 4, 'Some non-UTF-8 text',0, 'L');

You will get this error on PHP 8.1:

    Fatal error: Uncaught ValueError: max(): Argument #1 ($value) must contain at least one element in tcpdf.php:6412

This commit will show a useful error with the causing string

2023-03-07 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/tecnickcom/TCPDF?pullRequest=594) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/tecnickcom/TCPDF?pullRequest=594) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tecnickcom/TCPDF?pullRequest=594) it.</sub>

2023-03-07 19:10 UTC, williamdes requested changes
This does not feel like the right fix 🤔

2023-03-07 21:14 UTC, rubo77 commented
The problem is, that this line:
    // get array of unicode values
    $chars = TCPDF_FONTS::UTF8StringToArray($s, $this->isunicode, $this->CurrentFont);
	
sets $char to an empty array if $s contains non-utf8 characters

2023-03-07 21:49 UTC, rubo77 commented
I moved the error code generation into the function `UTF8StringToArray()`.

The problem always was before PHP8: if there are non-utf8- characters, the PDF generation was just ignoring this whole Cell, leaving it empty without warning.

This should enlight users a bit, what is going wrong then

2023-04-19 22:55 UTC, rubo77 commented
Maybe we should add `and !empty($str)` ?

2023-08-02 20:58 UTC, williamdes commented on include/tcpdf_fonts.php
> +				$carr = array_map(array('TCPDF_FONTS', 'uniord'), $chars);
please change this for PHP 8.2 compat, see #633 (#632)

2023-08-03 05:11 UTC, rubo77 commented
Please resolve this someone else. Sorry I don't have the time any more

2023-08-03 05:11 UTC, closed without merging