Fix #553 GD library error: imagecreatefrompng(): gd-png: libpng warning: iCCP: known incorrect sRGB profile
tecnickcom/TCPDF pull request #601
Opened 2023-03-24 14:48 UTC by lpetrora

It fixes issue reported in #553 by muting imagecreatefrompng.

2023-03-24 16:38 UTC, lpetrora commented
I have already signed the CLA but the status is still pending. I tried to recheck but there is no change

2023-03-24 16:56 UTC, williamdes commented
Please edit the description to use `Fixes: #553` or `Fix: #553`

2023-04-22 14:22 UTC, mvorisek commented on tcpdf.php
> +				$gdfunction = '@' . $gdfunction;
this cannot work - https://3v4l.org/lbu9o

2023-04-22 14:37 UTC, williamdes requested changes
Thanks for the testing @mvorisek 

This PR does not work correctly: https://github.com/tecnickcom/TCPDF/pull/601#discussion_r1174422155

2023-09-11 14:56 UTC, THenkeDE commented
to bypass this you have to add a helper variable like

```
			$gdfunction = 'imagecreatefrom'.$type;
			$silenceGdfunction = $type === 'png';
			...
					// GD library
					$img = $silenceGdfunction ? @$gdfunction($file) : $gdfunction($file);
```
but i have no idea if silencing a method was, is oder ever will be a good decision.

2024-10-26 10:37 UTC, nicolaasuni commented
It looks like this PR is not yet ready as there are unsolved comments.
I agree that suppressing errors is not actually a fix.
NOTE: the new tc-lib-pdf library has already a better image support if you can wait for the other HTML/CSS/SVG/Javascript features to be ported.

2024-10-26 21:59 UTC, closed without merging